baseURL: 
title: 欧阳松的博客
theme: hugo-theme-zzo
defaultContentLanguage: zh
defaultContentLanguageInSubdir: yes
hasCJKLanguage: yes
summaryLength: 80
buildFuture: yes
copyright: '&copy;{since 2021}, 欧阳松'
timeout: 10000
enableEmoji: yes
paginate: 13
rssLimit: 100
enableGitInfo: yes
googleAnalytics: ''
markup:
  goldmark:
    renderer:
      hardWraps: yes
      unsafe: yes
      xHTML: yes
  highlight:
    codeFences: yes
    lineNos: yes
    lineNumbersInTable: yes
    noClasses: no
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 2
outputs:
  home:
    - HTML
    - RSS
    - SearchIndex
  section:
    - HTML
    - RSS
    - SearchIndex
  taxonomy:
    - HTML
    - RSS
    - SearchIndex
  taxonomyTerm:
    - HTML
    - RSS
    - SearchIndex
outputFormats:
  SearchIndex:
    baseName: index
    isPlainText: yes
    mediaType: application/json
    notAlternative: yes
taxonomies:
  category: categories
  series: series
  tag: tags
